### ISSUE TITLE
[addwiki-api-base] Be able to specify assert=bot instead of assert=user

### ISSUE THREAD

**Issue by samwilson** [addwiki/addwiki#175]
`UserAndPassword::preRequestAuth()` currently adds `assert=user`, but it should be possible to have this be `assert=bot` when required.

https://github.com/addwiki/addwiki/blob/e3615e9eb829bc8fe917bb6bfb33e827a8c50327/packages/mediawiki-api-base/src/Client/Auth/UserAndPassword.php#L54

https://www.mediawiki.org/wiki/API:Assert

**Comment by berkantkockaya** [comment]
Hi, Sam To solve this issue;

	1.	Locate line 54 in the addwiki/packages/mediawiki-api-base/src/Client/Auth/UserAndPassword.php file.
	2.	Change the line $request->setParam( 'assert', 'user' ); to $request->setParam( 'assert', 'bot' );

**Comment by samwilson** [comment]
That's true, but it wouldn't fix the issue for anyone else.

I think it probably needs to do something similar to [how addwiki-api does it](https://github.com/addwiki/addwiki/blob/e3615e9eb829bc8fe917bb6bfb33e827a8c50327/packages/wikibase-api/src/WikibaseApi.php#L47), although I'm not quite sure what the best way is to pass an is-bot flag is. Perhaps the addition of `AuthMethod::isBot(): bool` and `AuthMethod::setBot( bool $bot )`?

**Comment by berkantkockaya** [comment]
To conditionally set the assert parameter in the preRequestAuth function, you can modify the function to accept an additional parameter that indicates whether the request is from a bot or a user. Here’s an example of how to implement this.

`function preRequestAuth($request, $isBot = false) {
    if ($isBot) {
        $request->setParam('assert', 'bot');
    } else {
        $request->setParam('assert', 'user');
    }
}`

This way, you can call preRequestAuth with the $isBot parameter set to true for bots and false for users, allowing the assert parameter to be set dynamically.

**Comment by samwilson** [comment]
(Just out of interest, are you using an AI tool to create that code?)

The `preRequstAuth()` method isn't usually called by the consuming code, it's called from `ActionApi::request()`, so it's not super convenient to change it there I think.

**Comment by samwilson** [comment]
Oh no, don't worry I'm not offended! :-) Just interested, because it's becoming more common to see generated code. It's often not quite the right code though!

Have you used the AddWiki package much?

**Comment by addshore** [comment]
How does https://github.com/addwiki/addwiki/commit/ce2679178304ac655a6be0f755493a203aee6f66 look for this case?

If you want to alter this param you can do...

```
new ActionApi( $this->apiUrl, (new UserAndPassword( 'CIUser', 'LongCIPass123' ))->setAssertType('foo') );
```

**Comment by samwilson** [comment]
Yep, that fixes it. Thanks!
